#if !canImport(ObjectiveC)
import XCTest

extension QuestionOntologyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuestionOntologyTests = [
        ("testDefinitions", testDefinitions),
        ("testInvalidClassEquivalencies2", testInvalidClassEquivalencies2),
        ("testInvalidClassEquivalencies", testInvalidClassEquivalencies),
        ("testInvalidPropertyEquivalencies", testInvalidPropertyEquivalencies),
        ("testInvalidSuperClasses", testInvalidSuperClasses),
        ("testInvalidSuperProperties", testInvalidSuperProperties),
        ("testInvalidTypes", testInvalidTypes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(QuestionOntologyTests.__allTests__QuestionOntologyTests),
    ]
}
#endif
